project_id = "gfzdxckeajqmjeshysyo"

[functions.analyze-health-data]
verify_jwt = true

[functions.process-lab-results]
verify_jwt = true

[functions.search-supplements]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false