// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfzdxckeajqmjeshysyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmemR4Y2tlYWpxbWplc2h5c3lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNzkxMjEsImV4cCI6MjA1MTc1NTEyMX0.-h3fOQD95qIsVqcI6Of-erA48tlwOL7cycg1D3STVyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);